[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[metadata]
name = "hestia"

[project]
name = "hestia"
version = "1.0"
requires-python = ">=3.7"

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]
log_cli = true
log_cli_level = "info"
