loop = true

[[programs]]
name = "Top"
heat_board = "Top"
heat_time = "20m"
temp_sensor = "TH1"
temp_abort = 85.0
cool_temp = 30.0

[[programs]]
name = "Bottom"
heat_board = "Bottom"
heat_time = "20m"
temp_sensor = "TH1"
temp_abort = 85.0
cool_temp = 30.0
