name: "Kibot PCB build"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/kibot*'
      - '*.kibot.yml'
      - 'scripts/kibot*'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '.github/workflows/kibot*'
      - '*.kibot.yml'
      - 'scripts/kibot*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quick:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6

    steps:
    - uses: actions/checkout@v2

    - name: kibot-build.sh
      run: |
        ./scripts/kibot-build.sh

    - name: Retrieve results
      uses: actions/upload-artifact@v2
      with:
        name: Automatic_outputs
        path: Generated
