name: "Kibot PCB build"

# Run the workflow on pushes with PCB or kibot config changes
on:
  push:
    paths:
      - 'hardware/pcb/**'
      - '.github/workflows/kibot*'
      - 'scripts/kibot*'

jobs:
  kibot:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:ki6.0.5_Debian

    steps:
    - uses: actions/checkout@v3

    - name: kibot-build.sh
      run: |
        ./scripts/kibot-build.sh

    - name: Save build output
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
