loop = false

[[programs]]
name = "Top hot"
heat_board = "Top"
heat_time = "3m"
temp_sensor = "TH3"
temp_abort = 90.0
thermostat = 80.0
cool_temp = 40.0

[[programs]]
name = "Bottom hot"
heat_board = "Bottom"
heat_time = "2m"
temp_sensor = "TH3"
temp_abort = 90.0
thermostat = 80.0
cool_temp = 40.0

[[programs]]
name = "Bottom warm"
heat_board = "Bottom"
heat_time = "3m"
heat_duty = 0.75
temp_sensor = "J7"
temp_abort = 60.0
cool_temp = 40.0
