[[programs]]
heat_board = "Top"
heat_time = "5s"
heat_duty = 1.0
temp_sensor = "TH1"
temp_abort = 80.0
cool_time = "10s"

[[programs]]
heat_board = "Bottom"
heat_time = "3s"
heat_duty = 1.0
temp_sensor = "J7"
temp_abort = 100.0
thermostat = 80.0
cool_time = "10s"
